### ISSUE TITLE
Make the project "more open"

### ISSUE THREAD

**Issue by Cpavrai** [InseeFrLab/cloud-scripts#1]
Somehow, variables are set for regions in [`config.tf`](https://github.com/InseeFrLab/cloud-scripts/blob/master/gke/config.tf) and domain name in [`populate.tf`](https://github.com/InseeFrLab/cloud-scripts/blob/master/gke/populate.tf).

It would be nice to have a config file for putting all this variable values, or to have a script whose job would to ask for this values to the user.

**Comment by olevitt** [comment]
Domain name has been set as a variable and the remaining configuration parameters are in a single location : `config.tf`. The `README` has been updated to explain how to configure it.
